### ISSUE TITLE
Discontinuous UV maps

### ISSUE THREAD

**Issue by onthez** [threejs/lwoloader#5]
Having used the loader over the past 6 months or so, the biggest pain point in authoring models that will successfully load is having to avoid discontinuous UV maps.  When you create a uv map in Lightwave it will almost certainly default to being discontinuous.

There are some manual techniques and a 3rd party plugin that can correct those down to basic UV maps but then there is a nasty trade off that the geometry is no long continuous so if applied to curved surface there is a hard unsmoothed edge where there shouldn't be one.

@looeee looked into this quite a bit and determined it might require a fair amount of effort.

I thought I would compile some resources to reference:

Current SDK docs (For LWO3) http://static.lightwave3d.com/sdk/2019/html/filefmts/lwo3.html#c_VMAD

Old SDK docs (For LWO2, but may have info that is still relevant) http://static.lightwave3d.com/sdk/11-6/html/filefmts/lwo2.html#c_VMAD

https://forums.newtek.com/showthread.php?112873-Dev-Parser-UV-Atlas-Mapping

https://forums.newtek.com/showthread.php?106629-Native-LWO-support-in-Unity/page2

This thread discusses going the other direction - bringing a model into LW, but has some good information.  Also a Lightwave dev chimed in to answer some questions which might be helpful.
https://forums.newtek.com/showthread.php?106234-Discontinuous-UV-handling-for-ObjectLoader-(in-C)

**Comment by looeee** [comment]
Thanks for this. Yeah, the issue is pretty thorny alright! 

The problem is **UV seams**, AKA discontinuities - that is, hard edge in UV maps. Lightwave and three.js handle them in very different ways and it's looking like quite a bit of work to convert. 

The simple way of understanding the way  this works in three.js is to examine the `BoxBufferGeometry`. 
If you apply a texture to the cube it will repeat six times, once for each face. However, we only have one UV map to accomplish this with, and each vertex must have only one associated UV coordinate. 
But each vertex is a corner on three faces of the cube, meaning that we need three UV coordinates for each vertex. 

The solution in three.js (and probably all real-time engines) is to duplicate each vertex 3 times, so that the cube actually has 24 vertices, rather than 6. 

The solution in Lightwave is to create 6 separate UV maps, and each vertex ends up with 3 coordinates. 

This is further complicated by the fact that there are two kinds of UV maps in lightwave - I think they are called VMAPS (continuous UVs) and VMADs (discontinuous UVs). In the case of the cube, these would be discontinuous UVs... at least, you'd think so . But, again as far as I recall, the UVs end up getting specified as a combination of VMAP and VMADs. 

The best thing to do here would be to create a couple of simple test models to work from:

1. two planes as right angles with same texture on both planes
2. a cube with same texture on all six faces

**Comment by looeee** [comment]
Tracking upstream in https://github.com/mrdoob/three.js/issues/19385
